# Generated by Django 5.0.4 on 2024-05-29 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_control', '0002_attempt_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge_control.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='selected_options',
            field=models.ManyToManyField(to='knowledge_control.option'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('attempt', 'user', 'question')},
        ),
    ]
